// Copyright 2026 Ilia Sazonov
// SPDX-License-Identifier: MIT

import Foundation
import OCIKit
import Testing

@testable import OCISessionBar

/// The JWK encoding is the one part of the sign-in flow with no SDK behind it, and
/// a wrong `n` or `e` fails late and opaquely — the Console simply refuses to issue
/// a token. So the parser is checked against a key generated by OpenSSL, with the
/// expected modulus and exponent taken from `openssl rsa -pubin -modulus -noout`
/// rather than from this implementation.
@Suite("JWK encoding")
struct JWKTests {
  static let publicKeyPEM = """
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoMU/NgU7FBv+xrOLo3bx
    GmXKtbNzgq3CMy/DlBs2tsC8yF1LViltUS3HSG7uPyYaU/u9Tnkhk0wTqYxUP1Ic
    DkszeE+VOMmC0j0P5hrDYp6zmTvAr4CaPTtxVCmcIlgd5ttewif2XG3OclgTl/GF
    Kf3agcUBtoi+sWsYxl1i89XbBDBsfHqXWPCEC+nnynSywvBCdEgNO3cj2O80Zanp
    zJgTpHAyZbQI/YLYVhS57KUd/NPcV7R9sz9B1+QgstNFcTdnwmW/m5VYfWePXjpB
    MX4irbrVxlzD70FzhLvNIogzdYnTHltLwXlIUtpnz867H7acN/NYu8f+mvjVGYup
    dwIDAQAB
    -----END PUBLIC KEY-----
    """

  /// `openssl rsa -pubin -in key.pem -modulus -noout`
  static let expectedModulusHex = """
    A0C53F36053B141BFEC6B38BA376F11A65CAB5B37382ADC2332FC3941B36B6C0BCC85D4B56296D51\
    2DC7486EEE3F261A53FBBD4E7921934C13A98C543F521C0E4B33784F9538C982D23D0FE61AC3629E\
    B3993BC0AF809A3D3B7154299C22581DE6DB5EC227F65C6DCE72581397F18529FDDA81C501B688BE\
    B16B18C65D62F3D5DB04306C7C7A9758F0840BE9E7CA74B2C2F04274480D3B7723D8EF3465A9E9CC\
    9813A4703265B408FD82D85614B9ECA51DFCD3DC57B47DB33F41D7E420B2D345713767C265BF9B95\
    587D678F5E3A41317E22ADBAD5C65CC3EF417384BBCD2288337589D31E5B4BC1794852DA67CFCEBB\
    1FB69C37F358BBC7FE9AF8D5198BA977
    """

  @Test("The modulus matches OpenSSL, byte for byte")
  func extractsModulus() throws {
    let (modulus, _) = try JWK.rsaComponents(spkiPEM: Self.publicKeyPEM)
    let hex = modulus.map { String(format: "%02X", $0) }.joined()
    #expect(hex == Self.expectedModulusHex)
    // 2048-bit key, and the leading DER sign byte must already be gone.
    #expect(modulus.count == 256)
  }

  @Test("The exponent is the standard 65537")
  func extractsExponent() throws {
    let (_, exponent) = try JWK.rsaComponents(spkiPEM: Self.publicKeyPEM)
    #expect(Array(exponent) == [0x01, 0x00, 0x01])
  }

  @Test("base64url uses the URL alphabet and drops padding")
  func encodesBase64URL() {
    // 0xFB 0xFF 0xBE encodes to "+/++" in standard base64, exercising both
    // substitutions at once.
    #expect(JWK.base64URLUnpadded(Data([0xFB, 0xFF, 0xBE])) == "-_--")
    // Three bytes need no padding; two bytes would gain one '=' and must not keep it.
    #expect(JWK.base64URLUnpadded(Data([0x01, 0x02])).contains("=") == false)
  }

  @Test("The public_key parameter decodes to a JWK carrying the real key")
  func buildsConsoleParameter() throws {
    let keyPair = try SessionKeyPair.generate()
    let parameter = try JWK.consolePublicKeyParameter(for: keyPair)

    // The outer encoding is base64url but keeps its padding, matching the CLI.
    #expect(parameter.contains("+") == false)
    #expect(parameter.contains("/") == false)

    let standard = parameter.replacing("-", with: "+").replacing("_", with: "/")
    let data = try #require(Data(base64Encoded: standard))
    let jwk = try #require(
      JSONSerialization.jsonObject(with: data) as? [String: String]
    )

    #expect(jwk["kty"] == "RSA")
    #expect(jwk["kid"] == "Ignored")
    // RFC 7518: the members are unpadded base64url.
    #expect(jwk["n"]?.contains("=") == false)
    #expect(jwk["e"] == "AQAB")  // 65537

    // And `n` really is this keypair's modulus, not some other key's.
    let (modulus, _) = try JWK.rsaComponents(spkiPEM: keyPair.publicKeyPEM)
    #expect(jwk["n"] == JWK.base64URLUnpadded(modulus))
  }

  @Test("A bare PKCS#1 key is accepted as well as a wrapped SPKI one")
  func acceptsPKCS1() throws {
    // Reconstructing the PKCS#1 body from the SPKI and re-parsing it exercises the
    // branch that swift-crypto would hit if it ever vended pkcs1DERRepresentation.
    let (modulus, exponent) = try JWK.rsaComponents(spkiPEM: Self.publicKeyPEM)
    let pkcs1 = DERWriter.sequence([
      DERWriter.integer(modulus),
      DERWriter.integer(exponent),
    ])
    let (roundTripped, roundTrippedExponent) = try JWK.rsaComponents(der: pkcs1)
    #expect(roundTripped == modulus)
    #expect(roundTrippedExponent == exponent)
  }

  @Test("Malformed input is reported, not misread")
  func rejectsGarbage() {
    #expect(throws: JWK.Failure.self) {
      try JWK.rsaComponents(spkiPEM: "-----BEGIN PUBLIC KEY-----\n!!!!\n-----END PUBLIC KEY-----")
    }
    #expect(throws: JWK.Failure.self) {
      // A SEQUENCE header promising more bytes than exist.
      try JWK.rsaComponents(der: Data([0x30, 0x82, 0x01, 0x00, 0x02, 0x01, 0x01]))
    }
    #expect(throws: JWK.Failure.self) {
      try JWK.rsaComponents(der: Data())
    }
  }
}

/// Just enough DER writing to build a test fixture.
private enum DERWriter {
  static func sequence(_ elements: [Data]) -> Data {
    tagged(0x30, elements.reduce(Data(), +))
  }

  static func integer(_ magnitude: Data) -> Data {
    // Re-add the sign byte if the high bit is set, which is what a DER encoder does.
    let body = (magnitude.first ?? 0) & 0x80 != 0 ? Data([0x00]) + magnitude : magnitude
    return tagged(0x02, body)
  }

  private static func tagged(_ tag: UInt8, _ body: Data) -> Data {
    var out = Data([tag])
    let count = body.count
    if count < 0x80 {
      out.append(UInt8(count))
    } else {
      var lengthBytes: [UInt8] = []
      var remaining = count
      while remaining > 0 {
        lengthBytes.insert(UInt8(remaining & 0xFF), at: 0)
        remaining >>= 8
      }
      out.append(UInt8(0x80 | lengthBytes.count))
      out.append(contentsOf: lengthBytes)
    }
    return out + body
  }
}
